// ENTERPRISE FIX: Legacy Migration Phase 3 - Professional PDF Reporting - 2026-02-27
import { BadRequestException, Injectable } from '@nestjs/common';
import * as puppeteer from 'puppeteer';

export type PrintableReportType = 'dashboard' | 'items' | 'transactions';
export type PrintReportPayload = {
  type: PrintableReportType;
  data: Record<string, unknown>;
  title?: string;
  subtitle?: string;
  generatedBy?: string;
  filename?: string;
};

type PrintColumn = {
  key: string;
  label: string;
  align?: 'left' | 'center' | 'right';
};

type PrintSummary = {
  label: string;
  value: string;
};

type ResolvedPrintModel = {
  title: string;
  subtitle: string;
  generatedBy: string;
  columns: PrintColumn[];
  rows: Array<Record<string, unknown>>;
  summary: PrintSummary[];
};

@Injectable()
export class ReportService {
  private readonly defaultColumnsByType: Record<PrintableReportType, PrintColumn[]> = {
    dashboard: [
      { key: 'date', label: 'Date', align: 'left' },
      { key: 'action', label: 'Action', align: 'left' },
      { key: 'user', label: 'User', align: 'left' },
      { key: 'item', label: 'Item', align: 'left' },
      { key: 'amount', label: 'Amount', align: 'right' },
    ],
    items: [
      { key: 'code', label: 'Code', align: 'left' },
      { key: 'name', label: 'Name', align: 'left' },
      { key: 'category', label: 'Category', align: 'left' },
      { key: 'unit', label: 'Unit', align: 'left' },
      { key: 'currentStock', label: 'Current Stock', align: 'right' },
      { key: 'minLimit', label: 'Min Limit', align: 'right' },
      { key: 'maxLimit', label: 'Max Limit', align: 'right' },
    ],
    transactions: [
      { key: 'date', label: 'Date', align: 'left' },
      { key: 'type', label: 'Type', align: 'left' },
      { key: 'itemName', label: 'Item', align: 'left' },
      { key: 'quantity', label: 'Quantity', align: 'right' },
      { key: 'supplierOrReceiver', label: 'Partner', align: 'left' },
      { key: 'warehouseInvoice', label: 'Invoice', align: 'left' },
      { key: 'createdByUserId', label: 'User', align: 'left' },
    ],
  };

  async generateReportPdf(
    payload: PrintReportPayload,
  ): Promise<{ buffer: Buffer; filename: string }> {
    const model = this.resolvePrintModel(payload);
    const html = this.buildHtmlTemplate(model);

    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });

    try {
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });

      const pdf = await page.pdf({
        format: 'A4',
        printBackground: true,
        displayHeaderFooter: true,
        margin: {
          top: '64px',
          bottom: '64px',
          left: '20px',
          right: '20px',
        },
        headerTemplate: `
          <div style="width:100%; padding:0 20px; font-size:9px; color:#475569; text-align:center;">
            FeedFactory Pro - ${this.escapeHtml(model.title)}
          </div>
        `,
        footerTemplate: `
          <div style="width:100%; padding:0 20px; font-size:9px; color:#64748b; display:flex; justify-content:space-between;">
            <span>Generated by FeedFactory Pro</span>
            <span>Page <span class="pageNumber"></span> / <span class="totalPages"></span></span>
          </div>
        `,
      });

      return {
        buffer: Buffer.from(pdf),
        filename: this.buildFilename(payload.filename || payload.title || `${payload.type}-report`),
      };
    } finally {
      await browser.close();
    }
  }

  buildExampleTemplate(): string {
    return this.buildHtmlTemplate({
      title: 'Example Professional Report',
      subtitle: 'Legacy Migration Phase 3',
      generatedBy: 'System',
      columns: this.defaultColumnsByType.items,
      rows: [
        {
          code: 'ITM-001',
          name: 'Corn Feed',
          category: 'Raw Material',
          unit: 'Kg',
          currentStock: 1500,
          minLimit: 250,
          maxLimit: 5000,
        },
      ],
      summary: [
        { label: 'Rows', value: '1' },
        { label: 'Generated At', value: new Date().toISOString() },
      ],
    });
  }

  private resolvePrintModel(payload: PrintReportPayload): ResolvedPrintModel {
    const type = payload.type;
    const rawData = payload.data ?? {};

    const generatedBy = String(payload.generatedBy || 'System User');
    const title = String(payload.title || this.defaultTitle(type));
    const subtitle = String(payload.subtitle || `Report Type: ${type}`);

    const columns = this.extractColumns(rawData, type);
    const rows = this.extractRows(rawData, type);
    const summary = this.extractSummary(rawData, type, rows.length);

    if (!rows.length) {
      throw new BadRequestException('No rows available for PDF generation.');
    }
    if (!columns.length) {
      throw new BadRequestException('No columns available for PDF generation.');
    }

    return {
      title,
      subtitle,
      generatedBy,
      columns,
      rows,
      summary,
    };
  }

  private extractColumns(data: Record<string, unknown>, type: PrintableReportType): PrintColumn[] {
    const customColumns = Array.isArray((data as any)?.columns) ? ((data as any).columns as any[]) : [];
    if (customColumns.length > 0) {
      return customColumns
        .map((col) => ({
          key: String(col?.key || ''),
          label: String(col?.label || col?.key || ''),
          align: this.resolveAlign(col?.align),
        }))
        .filter((col) => col.key && col.label)
        .slice(0, 20);
    }
    return this.defaultColumnsByType[type];
  }

  private extractRows(data: Record<string, unknown>, type: PrintableReportType): Array<Record<string, unknown>> {
    if (Array.isArray((data as any)?.rows)) return ((data as any).rows as Array<Record<string, unknown>>).slice(0, 5000);
    if (Array.isArray((data as any)?.items)) return ((data as any).items as Array<Record<string, unknown>>).slice(0, 5000);
    if (Array.isArray((data as any)?.transactions)) {
      return ((data as any).transactions as Array<Record<string, unknown>>).slice(0, 5000);
    }
    if (Array.isArray((data as any)?.recentActivity)) {
      return ((data as any).recentActivity as Array<Record<string, unknown>>).slice(0, 5000);
    }
    if (Array.isArray(data as unknown)) return (data as unknown as Array<Record<string, unknown>>).slice(0, 5000);
    throw new BadRequestException(`Unsupported data shape for "${type}" report.`);
  }

  private extractSummary(
    data: Record<string, unknown>,
    type: PrintableReportType,
    rowCount: number,
  ): PrintSummary[] {
    const customSummary = Array.isArray((data as any)?.summary) ? ((data as any).summary as any[]) : [];
    if (customSummary.length > 0) {
      return customSummary
        .map((entry) => ({
          label: String(entry?.label || ''),
          value: String(entry?.value || ''),
        }))
        .filter((entry) => entry.label);
    }

    if (type === 'dashboard') {
      return [
        { label: 'Total Items', value: String((data as any)?.totalItems ?? '-') },
        { label: 'Low Stock', value: String((data as any)?.lowStock ?? '-') },
        { label: 'Today Transactions', value: String((data as any)?.todayTransactions ?? '-') },
        { label: 'Total Revenue', value: String((data as any)?.totalRevenue ?? '-') },
      ];
    }

    if (type === 'transactions') {
      const rows = this.extractRows(data, type);
      const inbound = rows.filter((r) => {
        const v = String(r.type || '').toLowerCase();
        return (
          v.includes('in') ||
          v.includes('inbound') ||
          v.includes('incoming') ||
          v.includes('production') ||
          v.includes('7�"�7�"�7�"�#���"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�') ||
          v.includes('7�"�7�"�7�"�7�"�7�"�7�"�7�"�#�⬑"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�') ||
          v.includes('7�"�7�"�7�"�7�"�7�"�7�"�7�"�#�⬑"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�7�"�')
        );
      }).length;
      return [
        { label: 'Total Rows', value: String(rowCount) },
        { label: 'Inbound Rows', value: String(inbound) },
        { label: 'Outbound Rows', value: String(Math.max(0, rowCount - inbound)) },
      ];
    }

    return [{ label: 'Total Rows', value: String(rowCount) }];
  }

  private buildHtmlTemplate(model: ResolvedPrintModel): string {
    const renderedAt = new Date().toLocaleString('en-GB', { hour12: false });
    const headerCells = model.columns
      .map((col) => `<th class="align-${col.align || 'left'}">${this.escapeHtml(col.label)}</th>`)
      .join('');

    const bodyRows = model.rows
      .map((row) => {
        const cells = model.columns
          .map((col) => {
            const value = this.formatCellValue((row as Record<string, unknown>)[col.key]);
            return `<td class="align-${col.align || 'left'}">${this.escapeHtml(value)}</td>`;
          })
          .join('');
        return `<tr>${cells}</tr>`;
      })
      .join('');

    const summaryHtml = model.summary.length
      ? `
      <section class="summary-grid">
        ${model.summary
          .map(
            (entry) => `
            <div class="summary-card">
              <p class="summary-label">${this.escapeHtml(entry.label)}</p>
              <p class="summary-value">${this.escapeHtml(entry.value)}</p>
            </div>
          `,
          )
          .join('')}
      </section>
    `
      : '';

    return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${this.escapeHtml(model.title)}</title>
    <style>
      :root {
        --ink: #0f172a;
        --muted: #64748b;
        --line: #cbd5e1;
        --soft: #f8fafc;
      }
      * { box-sizing: border-box; }
      body {
        margin: 0;
        color: var(--ink);
        font-family: "Segoe UI", Tahoma, Arial, sans-serif;
        font-size: 12px;
        line-height: 1.45;
        background: #fff;
      }
      .sheet { padding: 24px 8px 0; }
      .report-header {
        display: flex;
        justify-content: space-between;
        align-items: flex-start;
        gap: 14px;
        margin-bottom: 12px;
      }
      .brand {
        display: flex;
        align-items: center;
        gap: 10px;
      }
      .logo {
        width: 34px;
        height: 34px;
        border-radius: 8px;
        background: linear-gradient(135deg, #0f766e, #0891b2);
        color: white;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 13px;
        font-weight: 700;
      }
      .brand h1 {
        margin: 0;
        font-size: 18px;
      }
      .brand p {
        margin: 2px 0 0;
        color: var(--muted);
        font-size: 11px;
      }
      .meta {
        text-align: right;
        font-size: 11px;
        color: var(--muted);
      }
      .title {
        margin: 10px 0 4px;
        font-size: 16px;
        font-weight: 700;
      }
      .subtitle {
        margin: 0 0 10px;
        color: var(--muted);
        font-size: 12px;
      }
      .summary-grid {
        display: grid;
        grid-template-columns: repeat(3, minmax(0, 1fr));
        gap: 8px;
        margin-bottom: 12px;
      }
      .summary-card {
        border: 1px solid var(--line);
        border-radius: 8px;
        background: var(--soft);
        padding: 8px 10px;
      }
      .summary-label {
        margin: 0;
        color: var(--muted);
        font-size: 10px;
      }
      .summary-value {
        margin: 3px 0 0;
        font-size: 13px;
        font-weight: 700;
      }
      table {
        width: 100%;
        border-collapse: collapse;
        border-spacing: 0;
      }
      thead th {
        background: #e2e8f0;
        border: 1px solid var(--line);
        padding: 8px 7px;
        font-weight: 700;
        font-size: 11px;
      }
      tbody td {
        border: 1px solid var(--line);
        padding: 7px 7px;
      }
      tbody tr:nth-child(even) td {
        background: #f8fafc;
      }
      .align-left { text-align: left; }
      .align-center { text-align: center; }
      .align-right { text-align: right; }
      .footer-note {
        margin-top: 10px;
        color: var(--muted);
        font-size: 10px;
      }
    </style>
  </head>
  <body>
    <main class="sheet">
      <header class="report-header">
        <div class="brand">
          <div class="logo">FF</div>
          <div>
            <h1>FeedFactory Pro</h1>
            <p>Professional Reporting Suite</p>
          </div>
        </div>
        <div class="meta">
          <div><strong>Generated:</strong> ${this.escapeHtml(renderedAt)}</div>
          <div><strong>By:</strong> ${this.escapeHtml(model.generatedBy)}</div>
        </div>
      </header>

      <h2 class="title">${this.escapeHtml(model.title)}</h2>
      <p class="subtitle">${this.escapeHtml(model.subtitle)}</p>

      ${summaryHtml}

      <table>
        <thead><tr>${headerCells}</tr></thead>
        <tbody>${bodyRows}</tbody>
      </table>

      <p class="footer-note">Confidential report generated for operational use only.</p>
    </main>
  </body>
</html>`;
  }

  private defaultTitle(type: PrintableReportType): string {
    if (type === 'dashboard') return 'Dashboard Report';
    if (type === 'items') return 'Items Report';
    return 'Transactions Report';
  }

  private resolveAlign(value: unknown): 'left' | 'center' | 'right' {
    if (value === 'center' || value === 'right') return value;
    return 'left';
  }

  private formatCellValue(value: unknown): string {
    if (value == null) return '';
    if (value instanceof Date) return value.toISOString();
    if (typeof value === 'number') {
      return new Intl.NumberFormat('en-US', { maximumFractionDigits: 3 }).format(value);
    }
    if (typeof value === 'boolean') return value ? 'Yes' : 'No';
    if (Array.isArray(value)) return value.map((entry) => String(entry)).join(', ');
    if (typeof value === 'object') return JSON.stringify(value);
    return String(value);
  }

  private escapeHtml(value: unknown): string {
    return String(value ?? '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  private buildFilename(name: string): string {
    const normalized = String(name || 'report')
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9-_]+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');
    return normalized || 'report';
  }
}
